//! Names of every JSON-RPC method routed by `obu-host`.
//!
//! Generated by `node scripts/generate-wire-methods.mjs` from `wire/methods.json`.
//! Do not edit by hand.

#![allow(missing_docs)]

// lifecycle
pub const PING: &str = "ping";
pub const GET_INFO: &str = "getInfo";
// session
pub const GET_TABS: &str = "getTabs";
pub const GET_CURRENT_TAB: &str = "getCurrentTab";
pub const GET_SELECTED_TAB: &str = "getSelectedTab";
pub const CREATE_TAB: &str = "createTab";
pub const FINALIZE_TABS: &str = "finalizeTabs";
pub const CLAIM_USER_TAB: &str = "claimUserTab";
pub const GET_USER_TABS: &str = "getUserTabs";
pub const NAME_SESSION: &str = "nameSession";
// cdp
pub const ATTACH: &str = "attach";
pub const DETACH: &str = "detach";
pub const EXECUTE_CDP: &str = "executeCdp";
pub const MOVE_MOUSE: &str = "moveMouse";
// history
pub const GET_USER_HISTORY: &str = "getUserHistory";
// browser
pub const BROWSER_TABS_CONTENT: &str = "browser_tabs_content";
pub const BROWSER_VIEWPORT_SET: &str = "browser_viewport_set";
pub const BROWSER_VIEWPORT_RESET: &str = "browser_viewport_reset";
pub const BROWSER_VISIBILITY_SET: &str = "browser_visibility_set";
pub const BROWSER_VISIBILITY_GET: &str = "browser_visibility_get";
// lifecycle
pub const TURN_ENDED: &str = "turnEnded";
pub const YIELD_CONTROL: &str = "yieldControl";
pub const RESUME_CONTROL: &str = "resumeControl";
// tasks
pub const TASKS_LIST: &str = "tasksList";
pub const TASKS_EXPORT: &str = "tasksExport";
pub const TASKS_RESUME: &str = "tasksResume";
pub const TASKS_RESUME_COMPLETE: &str = "tasksResumeComplete";
// lifecycle
pub const CLEAR_LIFECYCLE_DIAGNOSTICS: &str = "clearLifecycleDiagnostics";
pub const EXECUTE_UNHANDLED_COMMAND: &str = "executeUnhandledCommand";
// playwright
pub const PLAYWRIGHT_LOCATOR_CLICK: &str = "playwright_locator_click";
pub const PLAYWRIGHT_LOCATOR_DBLCLICK: &str = "playwright_locator_dblclick";
pub const PLAYWRIGHT_LOCATOR_DOWNLOAD_MEDIA: &str = "playwright_locator_download_media";
pub const PLAYWRIGHT_LOCATOR_FILL: &str = "playwright_locator_fill";
pub const PLAYWRIGHT_LOCATOR_PRESS: &str = "playwright_locator_press";
pub const PLAYWRIGHT_LOCATOR_WAIT_FOR: &str = "playwright_locator_wait_for";
pub const PLAYWRIGHT_LOCATOR_COUNT: &str = "playwright_locator_count";
pub const PLAYWRIGHT_LOCATOR_SELECT_OPTION: &str = "playwright_locator_select_option";
pub const PLAYWRIGHT_LOCATOR_SET_CHECKED: &str = "playwright_locator_set_checked";
pub const PLAYWRIGHT_LOCATOR_IS_VISIBLE: &str = "playwright_locator_is_visible";
pub const PLAYWRIGHT_LOCATOR_IS_ENABLED: &str = "playwright_locator_is_enabled";
pub const PLAYWRIGHT_LOCATOR_ALL_TEXT_CONTENTS: &str = "playwright_locator_all_text_contents";
pub const PLAYWRIGHT_LOCATOR_TEXT_CONTENT: &str = "playwright_locator_text_content";
pub const PLAYWRIGHT_LOCATOR_INNER_TEXT: &str = "playwright_locator_inner_text";
pub const PLAYWRIGHT_LOCATOR_GET_ATTRIBUTE: &str = "playwright_locator_get_attribute";
pub const PLAYWRIGHT_LOCATOR_READ_ALL: &str = "playwright_locator_read_all";
pub const PLAYWRIGHT_LOCATOR_HOVER: &str = "playwright_locator_hover";
pub const PLAYWRIGHT_LOCATOR_BOUNDING_BOX: &str = "playwright_locator_bounding_box";
pub const PLAYWRIGHT_SCREENSHOT: &str = "playwright_screenshot";
pub const PLAYWRIGHT_ELEMENT_INFO: &str = "playwright_element_info";
pub const PLAYWRIGHT_ELEMENT_SCREENSHOT: &str = "playwright_element_screenshot";
pub const PLAYWRIGHT_DOM_SNAPSHOT: &str = "playwright_dom_snapshot";
pub const PLAYWRIGHT_WAIT_FOR_TIMEOUT: &str = "playwright_wait_for_timeout";
pub const PLAYWRIGHT_WAIT_FOR_URL: &str = "playwright_wait_for_url";
pub const PLAYWRIGHT_WAIT_FOR_LOAD_STATE: &str = "playwright_wait_for_load_state";
pub const PLAYWRIGHT_WAIT_FOR_FILE_CHOOSER: &str = "playwright_wait_for_file_chooser";
pub const PLAYWRIGHT_FILE_CHOOSER_SET_FILES: &str = "playwright_file_chooser_set_files";
pub const PLAYWRIGHT_WAIT_FOR_DOWNLOAD: &str = "playwright_wait_for_download";
pub const PLAYWRIGHT_DOWNLOAD_PATH: &str = "playwright_download_path";
// cua
pub const CUA_CLICK: &str = "cua_click";
pub const CUA_DBLCLICK: &str = "cua_dblclick";
pub const CUA_SCROLL: &str = "cua_scroll";
pub const CUA_TYPE: &str = "cua_type";
pub const CUA_KEYPRESS: &str = "cua_keypress";
pub const CUA_DRAG: &str = "cua_drag";
pub const CUA_MOVE: &str = "cua_move";
pub const CUA_DOWNLOAD_MEDIA: &str = "cua_download_media";
// clipboard
pub const TAB_CLIPBOARD_READ_TEXT: &str = "tab_clipboard_read_text";
pub const TAB_CLIPBOARD_WRITE_TEXT: &str = "tab_clipboard_write_text";
pub const TAB_CLIPBOARD_READ: &str = "tab_clipboard_read";
pub const TAB_CLIPBOARD_WRITE: &str = "tab_clipboard_write";
// dom-cua
pub const DOM_CUA_GET_VISIBLE_DOM: &str = "dom_cua_get_visible_dom";
pub const DOM_CUA_CLICK: &str = "dom_cua_click";
pub const DOM_CUA_DOUBLE_CLICK: &str = "dom_cua_double_click";
pub const DOM_CUA_SCROLL: &str = "dom_cua_scroll";
pub const DOM_CUA_TYPE: &str = "dom_cua_type";
pub const DOM_CUA_KEYPRESS: &str = "dom_cua_keypress";
pub const DOM_CUA_DOWNLOAD_MEDIA: &str = "dom_cua_download_media";
// tab
pub const TAB_GOTO: &str = "tab_goto";
pub const TAB_RELOAD: &str = "tab_reload";
pub const TAB_BACK: &str = "tab_back";
pub const TAB_FORWARD: &str = "tab_forward";
pub const TAB_CLOSE: &str = "tab_close";
pub const TAB_SCREENSHOT: &str = "tab_screenshot";
pub const TAB_WAIT_FOR_URL: &str = "tab_wait_for_url";
pub const TAB_WAIT_FOR_LOAD_STATE: &str = "tab_wait_for_load_state";
pub const TAB_CONTENT_EXPORT: &str = "tab_content_export";
pub const TAB_EVALUATE: &str = "tab_evaluate";
pub const TAB_SNAPSHOT_TEXT: &str = "tab_snapshot_text";
pub const TAB_DEV_EVENTS: &str = "tab_dev_events";
pub const TAB_URL: &str = "tab_url";
pub const TAB_TITLE: &str = "tab_title";

/// All inbound (SDK -> obu-host) method names.
pub const ALL_INBOUND_METHODS: &[&str] = &[
    PING,
    GET_INFO,
    GET_TABS,
    GET_CURRENT_TAB,
    GET_SELECTED_TAB,
    CREATE_TAB,
    FINALIZE_TABS,
    CLAIM_USER_TAB,
    GET_USER_TABS,
    NAME_SESSION,
    ATTACH,
    DETACH,
    EXECUTE_CDP,
    MOVE_MOUSE,
    GET_USER_HISTORY,
    BROWSER_TABS_CONTENT,
    BROWSER_VIEWPORT_SET,
    BROWSER_VIEWPORT_RESET,
    BROWSER_VISIBILITY_SET,
    BROWSER_VISIBILITY_GET,
    TURN_ENDED,
    YIELD_CONTROL,
    RESUME_CONTROL,
    TASKS_LIST,
    TASKS_EXPORT,
    TASKS_RESUME,
    TASKS_RESUME_COMPLETE,
    CLEAR_LIFECYCLE_DIAGNOSTICS,
    EXECUTE_UNHANDLED_COMMAND,
    PLAYWRIGHT_LOCATOR_CLICK,
    PLAYWRIGHT_LOCATOR_DBLCLICK,
    PLAYWRIGHT_LOCATOR_DOWNLOAD_MEDIA,
    PLAYWRIGHT_LOCATOR_FILL,
    PLAYWRIGHT_LOCATOR_PRESS,
    PLAYWRIGHT_LOCATOR_WAIT_FOR,
    PLAYWRIGHT_LOCATOR_COUNT,
    PLAYWRIGHT_LOCATOR_SELECT_OPTION,
    PLAYWRIGHT_LOCATOR_SET_CHECKED,
    PLAYWRIGHT_LOCATOR_IS_VISIBLE,
    PLAYWRIGHT_LOCATOR_IS_ENABLED,
    PLAYWRIGHT_LOCATOR_ALL_TEXT_CONTENTS,
    PLAYWRIGHT_LOCATOR_TEXT_CONTENT,
    PLAYWRIGHT_LOCATOR_INNER_TEXT,
    PLAYWRIGHT_LOCATOR_GET_ATTRIBUTE,
    PLAYWRIGHT_LOCATOR_READ_ALL,
    PLAYWRIGHT_LOCATOR_HOVER,
    PLAYWRIGHT_LOCATOR_BOUNDING_BOX,
    PLAYWRIGHT_SCREENSHOT,
    PLAYWRIGHT_ELEMENT_INFO,
    PLAYWRIGHT_ELEMENT_SCREENSHOT,
    PLAYWRIGHT_DOM_SNAPSHOT,
    PLAYWRIGHT_WAIT_FOR_TIMEOUT,
    PLAYWRIGHT_WAIT_FOR_URL,
    PLAYWRIGHT_WAIT_FOR_LOAD_STATE,
    PLAYWRIGHT_WAIT_FOR_FILE_CHOOSER,
    PLAYWRIGHT_FILE_CHOOSER_SET_FILES,
    PLAYWRIGHT_WAIT_FOR_DOWNLOAD,
    PLAYWRIGHT_DOWNLOAD_PATH,
    CUA_CLICK,
    CUA_DBLCLICK,
    CUA_SCROLL,
    CUA_TYPE,
    CUA_KEYPRESS,
    CUA_DRAG,
    CUA_MOVE,
    CUA_DOWNLOAD_MEDIA,
    TAB_CLIPBOARD_READ_TEXT,
    TAB_CLIPBOARD_WRITE_TEXT,
    TAB_CLIPBOARD_READ,
    TAB_CLIPBOARD_WRITE,
    DOM_CUA_GET_VISIBLE_DOM,
    DOM_CUA_CLICK,
    DOM_CUA_DOUBLE_CLICK,
    DOM_CUA_SCROLL,
    DOM_CUA_TYPE,
    DOM_CUA_KEYPRESS,
    DOM_CUA_DOWNLOAD_MEDIA,
    TAB_GOTO,
    TAB_RELOAD,
    TAB_BACK,
    TAB_FORWARD,
    TAB_CLOSE,
    TAB_SCREENSHOT,
    TAB_WAIT_FOR_URL,
    TAB_WAIT_FOR_LOAD_STATE,
    TAB_CONTENT_EXPORT,
    TAB_EVALUATE,
    TAB_SNAPSHOT_TEXT,
    TAB_DEV_EVENTS,
    TAB_URL,
    TAB_TITLE,
];

/// Backend support state for a wire method.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendMethodSupport {
    Implemented,
    Unsupported,
    IntentionallyNotImplemented,
}

/// Backend support matrix generated from the wire method manifest.
pub const BACKEND_METHOD_SUPPORT: &[(&str, BackendMethodSupport, BackendMethodSupport)] = &[
    (
        PING,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_INFO,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_TABS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_CURRENT_TAB,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_SELECTED_TAB,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CREATE_TAB,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        FINALIZE_TABS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CLAIM_USER_TAB,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_USER_TABS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        NAME_SESSION,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        ATTACH,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DETACH,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        EXECUTE_CDP,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        MOVE_MOUSE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        GET_USER_HISTORY,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        BROWSER_TABS_CONTENT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        BROWSER_VIEWPORT_SET,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        BROWSER_VIEWPORT_RESET,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        BROWSER_VISIBILITY_SET,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        BROWSER_VISIBILITY_GET,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TURN_ENDED,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        YIELD_CONTROL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        RESUME_CONTROL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TASKS_LIST,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TASKS_EXPORT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TASKS_RESUME,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TASKS_RESUME_COMPLETE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CLEAR_LIFECYCLE_DIAGNOSTICS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        EXECUTE_UNHANDLED_COMMAND,
        BackendMethodSupport::IntentionallyNotImplemented,
        BackendMethodSupport::IntentionallyNotImplemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_CLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_DBLCLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_DOWNLOAD_MEDIA,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_FILL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_PRESS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_WAIT_FOR,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_COUNT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_SELECT_OPTION,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_SET_CHECKED,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_IS_VISIBLE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_IS_ENABLED,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_ALL_TEXT_CONTENTS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_TEXT_CONTENT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_INNER_TEXT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_GET_ATTRIBUTE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_READ_ALL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_HOVER,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_LOCATOR_BOUNDING_BOX,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_SCREENSHOT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_ELEMENT_INFO,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_ELEMENT_SCREENSHOT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_DOM_SNAPSHOT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_WAIT_FOR_TIMEOUT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_WAIT_FOR_URL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_WAIT_FOR_LOAD_STATE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_WAIT_FOR_FILE_CHOOSER,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_FILE_CHOOSER_SET_FILES,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_WAIT_FOR_DOWNLOAD,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        PLAYWRIGHT_DOWNLOAD_PATH,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_CLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_DBLCLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_SCROLL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_TYPE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_KEYPRESS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_DRAG,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_MOVE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        CUA_DOWNLOAD_MEDIA,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CLIPBOARD_READ_TEXT,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CLIPBOARD_WRITE_TEXT,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CLIPBOARD_READ,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CLIPBOARD_WRITE,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_GET_VISIBLE_DOM,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_CLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_DOUBLE_CLICK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_SCROLL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_TYPE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_KEYPRESS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        DOM_CUA_DOWNLOAD_MEDIA,
        BackendMethodSupport::Unsupported,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_GOTO,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_RELOAD,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_BACK,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_FORWARD,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CLOSE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_SCREENSHOT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_WAIT_FOR_URL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_WAIT_FOR_LOAD_STATE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_CONTENT_EXPORT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_EVALUATE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_SNAPSHOT_TEXT,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_DEV_EVENTS,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_URL,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
    (
        TAB_TITLE,
        BackendMethodSupport::Implemented,
        BackendMethodSupport::Implemented,
    ),
];

/// Methods advertised as unsupported by the cdp backend.
pub const CDP_UNSUPPORTED_METHODS: &[&str] = &[
    GET_USER_HISTORY,
    BROWSER_VIEWPORT_SET,
    BROWSER_VIEWPORT_RESET,
    BROWSER_VISIBILITY_SET,
    BROWSER_VISIBILITY_GET,
    CUA_DOWNLOAD_MEDIA,
    TAB_CLIPBOARD_READ_TEXT,
    TAB_CLIPBOARD_WRITE_TEXT,
    TAB_CLIPBOARD_READ,
    TAB_CLIPBOARD_WRITE,
    DOM_CUA_DOWNLOAD_MEDIA,
];

/// Methods advertised as unsupported by the webextension backend.
pub const WEBEXTENSION_UNSUPPORTED_METHODS: &[&str] = &[];

/// Methods marked intentionally-not-implemented for the cdp backend.
pub const CDP_INTENTIONALLY_NOT_IMPLEMENTED_METHODS: &[&str] = &[EXECUTE_UNHANDLED_COMMAND];

/// Methods marked intentionally-not-implemented for the webextension backend.
pub const WEBEXTENSION_INTENTIONALLY_NOT_IMPLEMENTED_METHODS: &[&str] =
    &[EXECUTE_UNHANDLED_COMMAND];
